/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.helmo.gbeditor;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.helmo.gbeditor.presenters.MainPresenter;
import org.helmo.gbeditor.presenters.Presenter;
import org.helmo.gbeditor.presenters.StartPresenter;
import org.helmo.gbeditor.repo.dbRepo;
import org.helmo.gbeditor.views.ContainerView;
import org.helmo.gbeditor.views.StartView;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        ContainerView cv = new ContainerView();
        StartView v = new StartView();

        MainPresenter p = new MainPresenter(cv);
        Presenter ps = new StartPresenter(v, p, new dbRepo("ip:port"));

        cv.setPresenter(p);

        cv.changeView(v, ps);

        Parent root = cv.getRoot();

        Scene scene = new Scene(root, 1000,600);

        scene.getStylesheets().add(getClass().getResource("/styles.css").toExternalForm());

        primaryStage.setTitle("Game book editor");
        primaryStage.setScene(scene);

        primaryStage.show();
    }
}